### PR TITLE
fix for rtl layouts

### PR DESCRIPTION
**Pull request by 4li-ra**
its animation has a problem in pages which has RTL layout

### CODE REVIEW

**Comment by zalog** [comment]
Hi @inscrutable0, and thanks for your time.
All the files in /dist/* must be generated through `npm run build` task. Could you please make another commit with files changed after running that npm task?

**Comment by zalog** [comment]
Hi @inscrutable0, and thanks for your time.
We'll generate files from `/dist/*` in another branch, the `release/*.*.*` ones.
Could you please undo modification from `/dist/*` folder?

**Comment by 4li-ra** [comment]
Hi @zalog , sorry about that, I didn't know.
I made a new PR.

**Comment by zalog** [comment]
No problem :)
You can just undo that modifications in another commit. There is no need to close this.

**Comment by zalog** [comment]
Closed because of #12

**Pull request closed without merging**
